### ISSUE TITLE
Resize machines bug

### ISSUE THREAD

**Issue by rphillips** [openshift/cluster-api#1]
Initially from https://github.com/openshift/machine-config-operator/issues/167

I initially instantiated a libvirt cluster with the default 2048 of RAM and 1 vcpu. I then edited the machineset via:
```
oc edit machineset --namespace openshift-cluster-api
```
and changed the vcpu to 4, the memory to 4096, and the replica count to 3. I expected to see all the workers get replaced with the higher requirements, but the original worker stayed at the default 2048 MB of RAM. The two new workers did get created correctly with the memory and vcpu requirements.

**Comment by bison** [comment]
Unfortunately, this isn't how it works currently. We're working on introducing the `MachineDeployment` resource in OpenShift. Using a higher level `MachineDeployment` instead of a `MachineSet` directly will enable this kind of rolling update.
